[features]
seeds = false
skip-lint = false

[programs.localnet]
draffle = "dRaFFLe111111111111111111111111111111111112"
community_staking = "9bZjYwx8yzVGjAtth8AuLCC6AY7Pts5jjX6T7Kb6iNEa"
dispenser = "B2jCF3V3hCCPcwsXPtjMhXVjzafXU68EMJWz3eKZ2kVa"

[programs.devnet]
draffle = "76HHTx3chJMqtXPXrxDgMJgSHbGUj8xmQBi7RoHc5zJD"
community_staking = "9bZjYwx8yzVGjAtth8AuLCC6AY7Pts5jjX6T7Kb6iNEa"
dispenser = "B2jCF3V3hCCPcwsXPtjMhXVjzafXU68EMJWz3eKZ2kVa"

[programs.mainnet]
draffle = "dRafA7ymQiLKjR5dmmdZC9RPX4EQUjqYFB3mWokRuDs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/8bit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
